name 'bpoint-generator'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bpoint-generator'
long_description 'Installs/Configures bpoint-generator'
version '0.1.0'
